### PR TITLE
restore filters data and all label constants

### PR DESCRIPTION
**Pull request by realturik**

### CODE REVIEW

**Comment by LTPrashant** [comment]
Can you please elaborate the use case solved in the request.

**Comment by realturik** [comment]
In my case I want to store filters settings and filtered data in redux and restore it when I need.

I make a data table for documents list and want to save filters. I think if user will filter documents and go serf of them, he want to see same state when go back to documents list. So I need to restore filter data after component was remount. 



пятница, 23 февраля 2018 г., 14:56 +0700 от notifications@github.com  <notifications@github.com>:

**Comment by LTPrashant** [comment]
Ok thanks, will review

**Comment by realturik** [comment]
Thnx!



воскресенье, 4 марта 2018 г., 13:20 +0700 от notifications@github.com  <notifications@github.com>:

**Comment by cheekujha** [comment]
Here
[https://github.com/cheekujha/react-table-filter/tree/maintain_filter_state](https://github.com/cheekujha/react-table-filter/tree/maintain_filter_state)

try this

**Pull request closed without merging**
